- clean:
    - '~/.gitconfig'
    - '~/.gitignore_global'
    - '~/.gitmessage'
- link:
    ~/.gitconfig: tools/vcs/git/gitconfig
    ~/.gitignore_global: tools/vcs/git/gitignore_global
    ~/.gitmessage: tools/vcs/git/gitmessage
