- link:
    ~/.gitconfig: tools/vcs/git/gitconfig
    ~/.gitconfig_user: tools/vcs/git/gitconfig_user
    ~/.gitignore_global: tools/vcs/git/gitignore_global
    ~/.gitmessage: tools/vcs/git/gitmessage
