- clean:
    - '~/.vim'
    - '~/.vimrc'
- link:
    ~/.vim: editors/vim
    ~/.vimrc: editors/vim/vimrc
- shell:
    - description: Installing vim-plug plugins
      command: ./modules/vim/install-plugins.sh
      quiet: true
