# Allow local customizations in the ~/.zshrc_before_local file
if [ -f "$HOME/.zshrc_before_local" ]; then
    source "$HOME/.zshrc_before_local"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set ZSH_THEME to blank so starship can load
ZSH_THEME=""
# Load powerlevel10k if zsh version will support it if not fall back to powerlevel9k
# if [ $(echo "$(echo $ZSH_VERSION | cut -d'.' -f -2) >= 5.1" | bc) -eq 1 ]
# then
#     ZSH_THEME="powerlevel10k/powerlevel10k"
# else
#     ZSH_THEME="powerlevel9k/powerlevel9k"
# fi

# Auto update oh-my-zsh automatically without asking
zstyle ':omz:update' mode auto

# Timestamp in history command output format
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    git
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
    nvm
)

source $ZSH/oh-my-zsh.sh

# User configuration

# Control f goes forward a word
bindkey "^f" forward-word
# Control g deletes a word
bindkey "^g" backward-word

zstyle ':completion:*' menu select

# Source rustup shell startup script if present
if [ -f "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi

# Initialize starship for zsh
eval "$(starship init zsh)"

# Allow local customizations in the ~/.zshrc_after_local file
if [ -f "$HOME/.zshrc_after_local" ]; then
    source "$HOME/.zshrc_after_local"
fi
