- brew:
    - python3
    - go
    - rustup-init
    - node
    - typescript
    - yarn

- shell:
    - description: Initialize rustup
      command: rustup-init --no-modify-path -y
      quiet: true
