- brew:
    - mas
- cask:
    - the-unarchiver # decompressing utility
    - rectangle # Move and resize windows using keyboard shortcuts or snap areas
    - alt-tab # Windows-like alt-tab
- shell:
    - description: Installing Spark Email
      command: mas install 1176895641
      quiet: true
