- brew:
    - mas # CLI for the Mac App Store
- cask:
    - stats # shows mac stats
    - spotify # Music streaming
    - 1password # Password manager
    - obsidian # Notes
    - google-drive # Google Drive client
    - notion # Notes
    - obs # Streaming
    - tailscale-app # Overlay VPN network
