name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  linux-development:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install curl git bash zsh vim python3 tmux bc
      - uses: actions/checkout@v3
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          HOME=~/dotfiles-install-dir ./install-profile development
